name: todo_app
services:

    ngnix:
        image: nginix:alpine
        container_name: todo_app-ngnix
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/wwww
        networks:
            todo_app-network

    app:
        build:
            context: ./
            dockerfile: dockerfile
        container_name: todo_app-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
          - ./:/var/www
        networks:
            todo_app-network

    db:
        image: mysql:5.6
        container_name: todo_app-db
        restart: unless-stopped
        enviroment:
            - MYSQL_ROOT_PASSWORD=my-secret-pwd
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
        ports:
            - 3306:3306
        volumes:
           - todo_app_db_volume:/var/lib/mysql
        networks:
            todo_app-network

    networks:
        todo_app-network:
            driver: bridge
            name: todo_app-network


    volumes:
      todo_app_db_volume: